services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Define a senha para o root
      MYSQL_DATABASE: my_database         # Cria o banco de dados automaticamente
      MYSQL_USER: devdojo_user            # Cria um usuário adicional (não root)
      MYSQL_PASSWORD: devdojo             # Define a senha para o usuário adicional
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

volumes:
  mysql_data:
    driver: local
