server:
  port: 8080

  spring:
    application:
      name: course
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
        jmx:
          enabled: false
        datasource:
          url: mysql://root:my_password@<host>:3306/my_database
          username: my_user
          password: my_password


